project_id = "uhqxfttnjovuwhvhgclp"

[functions.fetch-twitch-vod]
verify_jwt = false

[functions.get-vod-stream]
verify_jwt = false

[functions.process-clip]
verify_jwt = false

[functions.proxy-vod]
verify_jwt = false

[functions.rewrite-m3u8]
verify_jwt = false
